version: 2

sources:
  - name: aw_production
    database: ADVENTURE_WORKS_RAW_DB
    schema: production
    loaded_at_field: _sdc_extracted_at
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 5000, period: day}
    tables:
      - name: product
      - name: productcategory
      - name: productmodel
      - name: productsubcategory