version: 2

sources:
  - name: aw_sales
    database: ADVENTURE_WORKS_RAW_DB
    schema: sales
    loaded_at_field: _sdc_extracted_at
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 5000, period: day}
    tables:
      - name: creditcard
      - name: customer
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesperson
      - name: salesreason
      - name: salesterritory
      - name: store