version: 2

sources:
  - name: aw_sales
    database: ADVENTURE_WORKS_RAW_DB  
    schema: sales
    tables: 
      - name: countryregioncurrency
      - name: creditcard
      - name: currency
      - name: currencyrate
      - name: customer
      - name: personcreditcard
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesperson
      - name: salespersonquotahistory
      - name: salesreason
      - name: salestaxrate
      - name: salesterritory
      - name: salesterritoryhistory
      - name: shoppingcartitem
      - name: specialoffer
      - name: specialofferproduct
      - name: store