version: 2

sources:
  - name: aw_humanresources
    database: ADVENTURE_WORKS_RAW_DB  
    schema: humanresources
    tables:
      - name: department
      - name: employee
      - name: employeedepartmenthistory
      - name: employeepayhistory
      - name: jobcandidate
      - name: shift
      - name: transactionhistory
