version: 2

sources:
  - name: aw_purchasing
    database: ADVENTURE_WORKS_RAW_DB  
    schema: purchasing
    tables:
      - name: productvendor
      - name: purchaseorderdetail
      - name: purchaseorderheader
      - name: shipmethod
      - name: vendor