version: 2

sources:
  - name: aw_person
    database: ADVENTURE_WORKS_RAW_DB
    schema: person
    loaded_at_field: _sdc_extracted_at
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 5000, period: day}
    tables:
      - name: address 
      - name: businessentityaddress
      - name: countryregion
      - name: person
      - name: stateprovince