version: 2

sources:
  - name: aw_person
    database: ADVENTURE_WORKS_RAW_DB  
    schema: person
    tables:
      - name: address
      - name: addresstype
      - name: businessentity 
      - name: businessentityaddress
      - name: businessentitycontact
      - name: contacttype
      - name: countryregion
      - name: emailaddress
      - name: person
      - name: personphone
      - name: stateprovince